# Makefile
BUSYBOX_REPO = git://busybox.net/busybox.git
CROSS_COMPILE = arm-linux-gnueabihf-
ARCH = arm
OUTPUT = busybox-rootfs.img

.PHONY: all clean

all: clone build package

clone:
	@echo "Cloning BusyBox repository..."
	git clone $(BUSYBOX_REPO) busybox-src

configure:
	cd busybox-src && make defconfig
	sed -i 's/.*CONFIG_STATIC.*/CONFIG_STATIC=y/' busybox-src/.config
	sed -i 's/.*CONFIG_UDHCPD.*/CONFIG_UDHCPD=y/' busybox-src/.config

build: configure
	@echo "Building BusyBox..."
	cd busybox-src && make CROSS_COMPILE=$(CROSS_COMPILE) ARCH=$(ARCH) -j$(nproc)
	mkdir -p rootfs
	cd busybox-src && make CROSS_COMPILE=$(CROSS_COMPILE) CONFIG_PREFIX=../rootfs install

package:
	@echo "Creating rootfs image..."
	# 创建初始化脚本
	mkdir -p rootfs/etc/init.d
	echo '#!/bin/sh\nmount -t proc proc /proc\nmount -t sysfs sysfs /sys' > rootfs/etc/init.d/rcS
	chmod +x rootfs/etc/init.d/rcS
	# 生成镜像
	genext2fs -b 8192 -d rootfs $(OUTPUT)
	mkimage -A $(ARCH) -O linux -T ramdisk -C none -a 0 -e 0 -n "BusyBox" -d $(OUTPUT) uRamdisk

clean:
	rm -rf busybox-src rootfs $(OUTPUT) uRamdisk
